server:
  port: 8081

spring:
  application:
    name: smart-inventory

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

inventario:
  stock:
    minimo: 10
    critico: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info